ARM64: config: Add missing configs
ERROR: files are incompatible: Runtime info and framework compatibility matrix are incompatible: No compatible kernel requirement found (kernel FCM version = 5).
For kernel requirements at matrix level 6, Kernel config errors:
    Missing config CONFIG_CRYPTO_CHACHA20POLY1305
    Missing config CONFIG_CRYPTO_XCBC
    Missing config CONFIG_XFRM_MIGRATE
: Success